# export Mesh,
#        modelExpand,
#        getABC,
#        getSommerfeldBC,
#        Dxx,
#        getLaplacian,
#        getHelmhotzMtx,
#        getAdjointMtx,
#        FSource,
#        miniPhase,
#        src2wfd,
#        sample,
#        insert,
#        getDataTime,
#        intercept,
# ==============modeling==============
       # window,
       # forwardOperator,
       # adjointOperator,
       # adjoint_stack,
       # CG_stack,
       # fpower,
       # ffista,
       # fsoftThresh,
       # CG,
       # PCG,
       # goodPass,
       # stackInversion,
       # getlambda,
       # getEig,
       # initRemoteChannel,
       # initChannel,
       # Location,
       # freqHost,
       # setupLocation,
       # updateDobs,
       # remoteFista,
       # parLocation,
# ========================================
       # sub_index2linear_index,
       # index_change,
       # num_nonzeros,
       # get_bulk,
       # damping_profile,
       # rho_average,
       # get_helmholtz_coef,
       # COOCSC,
       # helmholtz_matrix,
       # getWavefield_FDFD
export model_extend,
       init_pml,
       damping_profile,
       vel2mu_cmplx,
       rho2bu,
       bu_average,
       helmholtz_kernal,
       eval_helmholtz_matrix,
       eval_wavefield_FDFD,
       COOCSC,
       remove_repeated,
# ========================================
       amplitude_spectra,
       band_pass_filter,
       sinc_resample1D

# include("freqModel.jl")
# include("freqSolve.jl")
include("Helmholtz_SeisScope.jl")
include("amplitude_spectra.jl")
